# Form implementation generated from reading ui file 'parser.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(248, 308)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(20, 100, 211, 131))
        self.textEdit.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.pushButton_start = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(20, 10, 81, 61))
        self.pushButton_start.setStyleSheet("color: rgb(0, 255, 0);")
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_load_to_exel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_load_to_exel.setGeometry(QtCore.QRect(150, 10, 81, 61))
        self.pushButton_load_to_exel.setStyleSheet("color: rgb(0, 255, 0);")
        self.pushButton_load_to_exel.setObjectName("pushButton_load_to_exel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 248, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_start.setText(_translate("MainWindow", "Start"))
        self.pushButton_load_to_exel.setText(_translate("MainWindow", "Load_to_exel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
